;;; es-windows-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from es-windows.el

(autoload 'esw/select-window "es-windows" "\
Query for a window using PROMPT, select and return it.

If SHOW-INTERNAL-WINDOWS is non-nil, show their labels, and accept them as input.
If an internal window is selected, it's children will be deleted.

If ALLOW-SPLITTING is non-nil, provide the user an option to split windows.

(fn &optional PROMPT SHOW-INTERNAL-WINDOWS ALLOW-SPLITTING)" t)
(autoload 'esw/show-buffer "es-windows" "\
Show the selected buffer in the selected window.

(fn BUFFER)" t)
(autoload 'esw/move-window "es-windows" "\
Show current buffer in a different window, and delete the old window.

(fn WINDOW)" t)
(autoload 'esw/delete-window "es-windows" "\
Choose and delete a window." t)
(autoload 'esw/swap-two-windows "es-windows" "\
Choose and swap two windows." t)
(register-definition-prefixes "es-windows" '("esw/"))

;;; End of scraped data

(provide 'es-windows-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; es-windows-autoloads.el ends here
